#!/data/data/com.termux/files/usr/bin/sh
cd $PREFIX/bin
if [ -e ngrok ];then
echo
else
clear
printf "\033[91m [×] Ngrok not found !!!\n"
sleep 1
printf "\033[91m\n\n [+]\033[92m Downloading Ngrok....."
cd ~
wget https://github.com/rooted-cyber/upload/raw/master/ngrok.zip > /dev/null 2>&1
printf "\n\n\033[94m [√]\033[93m Download complete\n\n"
sleep 1
printf "\033[95m [+]\033[96m Unzip Ngrok.....\n\n"
unzip ngrok.zip
sleep 1
printf "\n\n\033[94m [√]\033[93m Unzip complete\n\n"
sleep 1
printf "\033[91m [-]\033[92m Installing ngrok...\n\n"
cp -f ngrok $PREFIX/bin
chmod 777 $PREFIX/bin/ngrok
sleep 1
printf "\n\n\033[94m [√]\033[93m Installing complete\n\n"
sleep 1
printf "\033[95m Now open open-tools....\n"
sleep 2
cd $HOME
bash .open.sh
fi

install_open () {
cd ~
apt update
apt upgrade
apt install git
git clone https://github.com/rooted-cyber/Open-ToolS
cd Open-ToolS
bash open.sh
}
cd ~
if [ -e Open-ToolS ];then
bash .open.sh
else
cd ~
printf "\n\n\033[91m Open-ToolS is not install !!\n\n"
echo -e "\033[92m Install Open-ToolS \033[91m(\033[93m Y/N\033[91m ) "
read o
case $o in
y|Y)install_open ;;
n|N)exit 0 ;;
*)open ;;
esac
fi
